services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "${API_PORT}:8000"
    command: "uvicorn --factory chessapp.interface.main:create_app --reload --timeout-graceful-shutdown 2 --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ..:/app/
    depends_on:
      kafka:
        condition: service_healthy
